# Import the datasets

In [34]:
import pandas as pd
import os

In [36]:
file_path = "Dataset"
files = os.listdir(file_path)

In [38]:
dataset1 = 'NBA_traditional_100.csv'
dataset2 = 'NBA_shooting.csv'
dataset3 = 'NBA_adv_stat.csv'

In [40]:
df1 = pd.read_csv(os.path.join(file_path,dataset1))
df2 = pd.read_csv(os.path.join(file_path,dataset2))
df3 = pd.read_csv(os.path.join(file_path,dataset3))

In [42]:
# Player traditional stats (per 100 possessions)

df1

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,AST,STL,BLK,TOV,PF,PTS,ORtg,DRtg,Awards,Player-additional
0,1,Amen Thompson,23,HOU,PG,79,79,2953,9.4,17.7,...,7.1,2.0,0.8,3.2,3.0,24.4,125.0,114,DPOY-8,thompam01
1,2,Kevin Durant,37,HOU,SF,78,78,2840,12.6,24.2,...,6.5,1.1,1.2,4.3,2.5,35.6,124.0,115,CPOY-9ASNBA2,duranke01
2,3,Desmond Bane,27,ORL,SG,82,82,2756,10.2,21.0,...,5.9,1.5,0.6,2.9,4.4,28.7,120.0,117,NaN,banede01
3,4,Toumani Camara,25,POR,PF,82,82,2731,6.9,15.6,...,3.5,1.6,0.6,2.5,4.1,19.2,115.0,116,NaN,camarto01
4,5,Jabari Smith Jr.,22,HOU,PF,77,77,2705,8.1,18.0,...,2.6,1.0,1.3,1.9,3.5,22.4,120.0,114,NaN,smithja05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,578,Stanley Umude,26,SAS,SG,2,0,7,6.9,13.7,...,6.9,6.9,0.0,0.0,13.7,13.7,123.0,105,NaN,umudest01
729,579,Colby Jones,23,DET,SG,1,0,7,6.9,20.7,...,13.8,0.0,0.0,0.0,6.9,13.8,106.0,101,NaN,jonesco02
730,580,Noa Essengue,19,CHI,PF,2,0,6,0.0,23.4,...,0.0,7.8,0.0,0.0,7.8,0.0,0.0,109,NaN,essenno01
731,581,Trentyn Flowers,20,CHI,SF,2,0,6,15.6,23.4,...,7.8,0.0,0.0,7.8,7.8,31.2,110.0,127,NaN,flowetr01
732,582,Darius Brown II,26,CLE,SG,1,0,3,0.0,16.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,114,NaN,brownda04

In [44]:
# Player shooting statistics (showing shooting tendencies)

df2

,Rk,Player,Age,Team,Pos,G,GS,MP,FG%,Dist.,2P,% of FGA by 0-3 feet,% of FGA by 3-10 feet,% of FGA by 10-16 feet,% of FGA by 16 feet - 3P,% of FGA by 3P area,% of 2PFG Ast'd,% of 3P Ast'd,%3PA Corner
0,1,Amen Thompson,23,HOU,PG,79,79,2953,0.534,7.8,0.889,0.383,0.333,0.112,0.060,0.111,0.530,0.960,0.586
1,2,Kevin Durant,37,HOU,SF,78,78,2840,0.520,16.4,0.673,0.065,0.145,0.307,0.156,0.327,0.472,0.731,0.102
2,3,Desmond Bane,27,ORL,SG,82,82,2756,0.484,13.5,0.646,0.226,0.251,0.105,0.065,0.354,0.526,0.796,0.197
3,4,Toumani Camara,25,POR,PF,82,82,2731,0.440,18.1,0.336,0.175,0.135,0.020,0.006,0.664,0.659,0.886,0.296
4,5,Jabari Smith Jr.,22,HOU,PF,77,77,2705,0.450,16.8,0.499,0.137,0.147,0.155,0.061,0.501,0.670,0.966,0.357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,578,Stanley Umude,26,SAS,SG,2,0,7,0.500,16.4,0.500,0.000,0.500,0.000,0.000,0.500,1.000,NaN,1.000
729,579,Colby Jones,23,DET,SG,1,0,7,0.333,16.9,0.333,0.000,0.333,0.000,0.000,0.667,0.000,NaN,1.000
730,580,Noa Essengue,19,CHI,PF,2,0,6,0.000,16.9,0.333,0.333,0.000,0.000,0.000,0.667,NaN,NaN,0.500
731,581,Trentyn Flowers,20,CHI,SF,2,0,6,0.667,8.3,0.667,0.667,0.000,0.000,0.000,0.333,0.500,NaN,1.000
732,582,Darius Brown II,26,CLE,SG,1,0,3,0.000,17.5,1.000,0.000,0.000,0.000,1.000,0.000,NaN,NaN,NaN

In [46]:
# Player advanced statistics

df3

,Rk,Player,Age,Team,Pos,G,GS,MP,PER,TS%,...,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP,Awards,Player-additional
0,1,Amen Thompson,23,HOU,PG,79,79,2953,18.9,0.594,...,6.5,3.8,10.3,0.167,1.6,1.0,2.6,3.4,DPOY-8,thompam01
1,2,Kevin Durant,37,HOU,SF,78,78,2840,21.1,0.641,...,7.5,3.2,10.7,0.180,4.4,0.1,4.5,4.7,CPOY-9ASNBA2,duranke01
2,3,Desmond Bane,27,ORL,SG,82,82,2756,16.9,0.607,...,4.8,2.6,7.4,0.129,1.6,-0.2,1.4,2.3,NaN,banede01
3,4,Toumani Camara,25,POR,PF,82,82,2731,11.3,0.578,...,2.1,2.7,4.8,0.084,-1.0,0.0,-1.0,0.7,NaN,camarto01
4,5,Jabari Smith Jr.,22,HOU,PF,77,77,2705,13.5,0.570,...,3.4,3.3,6.6,0.118,-0.5,-0.2,-0.7,0.9,NaN,smithja05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
728,578,Stanley Umude,26,SAS,SG,2,0,7,11.6,0.500,...,0.0,0.0,0.0,0.165,-6.7,7.1,0.4,0.0,NaN,umudest01
729,579,Colby Jones,23,DET,SG,1,0,7,12.9,0.333,...,0.0,0.0,0.0,0.124,-3.2,5.7,2.4,0.0,NaN,jonesco02
730,580,Noa Essengue,19,CHI,PF,2,0,6,-11.9,0.000,...,-0.1,0.0,-0.1,-0.417,-20.7,-3.0,-23.7,0.0,NaN,essenno01
731,581,Trentyn Flowers,20,CHI,SF,2,0,6,16.7,0.667,...,0.0,0.0,0.0,0.023,1.7,-2.7,-1.0,0.0,NaN,flowetr01
732,582,Darius Brown II,26,CLE,SG,1,0,3,-7.7,0.000,...,0.0,0.0,0.0,-0.269,-16.3,-2.4,-18.7,0.0,NaN,brownda04

In [48]:
df_list = [df1, df2, df3]

for i in df_list:
    print(i['Player'].value_counts())

Player
Charles Bassey         5
Patrick Baldwin Jr.    4
Christian Koloko       4
RayJ Dennis            4
Tyus Jones             4
                      ..
Ben Sheppard           1
Kyshawn George         1
Gui Santos             1
Christian Braun        1
Darius Brown II        1
Name: count, Length: 582, dtype: int64
Player
Charles Bassey         5
Patrick Baldwin Jr.    4
Christian Koloko       4
RayJ Dennis            4
Tyus Jones             4
                      ..
Ben Sheppard           1
Kyshawn George         1
Gui Santos             1
Christian Braun        1
Darius Brown II        1
Name: count, Length: 582, dtype: int64
Player
Charles Bassey         5
Patrick Baldwin Jr.    4
Christian Koloko       4
RayJ Dennis            4
Tyus Jones             4
                      ..
Ben Sheppard           1
Kyshawn George         1
Gui Santos             1
Christian Braun        1
Darius Brown II        1
Name: count, Length: 582, dtype: int64

Noticed that some players in the data frames have multiple records. The main reason is that those players were traded to another team during the season.
For example, the first player in the data frame, Precious Achiuwa, contains 3 rows. The first row of the player contains the statistics for the whole season and the second and last rows represent the statistics for the old and current teams respectively. The duplication of players has to be re-moved. The last row of each duplicated player will remain and perfor-mance data will be replaced by the first row of the duplicated player.

## Data Cleaning

In [54]:
# Extract player with '2TM', '3TM' and '4TM' in column 'Team'

df1_multi_team = df1[(df1['Team'] == '2TM') | (df1['Team'] == '3TM') | (df1['Team'] == '4TM')]
df2_multi_team = df2[(df2['Team'] == '2TM') | (df2['Team'] == '3TM') | (df2['Team'] == '4TM')]
df3_multi_team = df3[(df3['Team'] == '2TM') | (df3['Team'] == '3TM') | (df3['Team'] == '4TM')]

In [56]:
def clean_nba_multi_team_records(df, df_multi_team, cols_to_drop=[]):
    """
    A dedicated function for processing player data from mid-season transfers.
    Overwrites a player's last team record with TOT (Total) total data and removes specified unnecessary fields.

    Parameters:
    - df: The original DataFrame containing all player season data (including individual team records)
    - df_tot: A DataFrame containing only the TOT (Total) data for transferred players
    - cols_to_drop: The list of feature fields to ultimately remove
    """
    
    df_working = df.copy()
    df_multi_team_working = df_multi_team.copy()
    
    # Create a new column 'ID' with unique numbers for each row
    df_working['ID'] = df_working.index + 1
    
    # Get the max ID of each player
    df_max_id_rows = df_working.loc[df_working.groupby('Player')['ID'].idxmax()].copy()
    df_max_id_rows = df_max_id_rows.sort_values(by='ID')
    
    # Set column 'Player' as the index of the dataframes
    df_max_id_rows.set_index('Player', inplace=True)
    df_multi_team_working.set_index('Player', inplace=True)
    
    # Update columns with performance data in df_max_id_rows using corresponding values from df_multi_team
    df_max_id_rows.update(df_multi_team_working)
    
    # Reset the index
    df_max_id_rows.reset_index(inplace=True)
    
    # Drop unnecessary columns
    cols_to_remove = cols_to_drop + ['ID']
    df_max_id_rows.drop(columns=cols_to_remove, axis=1, inplace=True, errors='ignore')
    
    return df_max_id_rows

In [82]:
df1_cleaned.columns

Index(['Player', 'Rk', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

In [68]:
df1_cleaned = clean_nba_multi_team_records(
    df = df1, 
    df_multi_team = df1_multi_team,
    cols_to_drop = ['ORtg', 'DRtg', 'Player-additional', 'Awards']
)

df1_cleaned

,Player,Rk,Age,Team,Pos,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,Amen Thompson,1,23,HOU,PG,79,79,2953,9.4,17.7,...,0.779,4.0,6.4,10.4,7.1,2.0,0.8,3.2,3.0,24.4
1,Kevin Durant,2,37,HOU,SF,78,78,2840,12.6,24.2,...,0.874,0.7,6.8,7.5,6.5,1.1,1.2,4.3,2.5,35.6
2,Desmond Bane,3,27,ORL,SG,82,82,2756,10.2,21.0,...,0.908,1.7,4.2,5.9,5.9,1.5,0.6,2.9,4.4,28.7
3,Toumani Camara,4,25,POR,PF,82,82,2731,6.9,15.6,...,0.708,2.3,5.1,7.4,3.5,1.6,0.6,2.5,4.1,19.2
4,Jabari Smith Jr.,5,22,HOU,PF,77,77,2705,8.1,18.0,...,0.775,2.0,7.8,9.8,2.6,1.0,1.3,1.9,3.5,22.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Stanley Umude,578,26,SAS,SG,2,0,7,6.9,13.7,...,NaN,0.0,0.0,0.0,6.9,6.9,0.0,0.0,13.7,13.7
578,Colby Jones,579,23,DET,SG,1,0,7,6.9,20.7,...,NaN,0.0,27.6,27.6,13.8,0.0,0.0,0.0,6.9,13.8
579,Noa Essengue,580,19,CHI,PF,2,0,6,0.0,23.4,...,NaN,0.0,0.0,0.0,0.0,7.8,0.0,0.0,7.8,0.0
580,Trentyn Flowers,581,20,CHI,SF,2,0,6,15.6,23.4,...,NaN,7.8,0.0,7.8,7.8,0.0,0.0,7.8,7.8,31.2
581,Darius Brown II,582,26,CLE,SG,1,0,3,0.0,16.0,...,NaN,0.0,16.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0

In [84]:
df2_cleaned = clean_nba_multi_team_records(
    df = df2, 
    df_multi_team = df2_multi_team,
    cols_to_drop = ['Rk', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG%', '2P']
)

df2_cleaned

,Player,Dist.,% of FGA by 0-3 feet,% of FGA by 3-10 feet,% of FGA by 10-16 feet,% of FGA by 16 feet - 3P,% of FGA by 3P area,% of 2PFG Ast'd,% of 3P Ast'd,%3PA Corner
0,Amen Thompson,7.8,0.383,0.333,0.112,0.060,0.111,0.530,0.960,0.586
1,Kevin Durant,16.4,0.065,0.145,0.307,0.156,0.327,0.472,0.731,0.102
2,Desmond Bane,13.5,0.226,0.251,0.105,0.065,0.354,0.526,0.796,0.197
3,Toumani Camara,18.1,0.175,0.135,0.020,0.006,0.664,0.659,0.886,0.296
4,Jabari Smith Jr.,16.8,0.137,0.147,0.155,0.061,0.501,0.670,0.966,0.357
...,...,...,...,...,...,...,...,...,...,...
577,Stanley Umude,16.4,0.000,0.500,0.000,0.000,0.500,1.000,NaN,1.000
578,Colby Jones,16.9,0.000,0.333,0.000,0.000,0.667,0.000,NaN,1.000
579,Noa Essengue,16.9,0.333,0.000,0.000,0.000,0.667,NaN,NaN,0.500
580,Trentyn Flowers,8.3,0.667,0.000,0.000,0.000,0.333,0.500,NaN,1.000
581,Darius Brown II,17.5,0.000,0.000,0.000,1.000,0.000,NaN,NaN,NaN

In [86]:
df3_cleaned.columns

Index(['Player', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%', 'AST%',
       'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48', 'OBPM',
       'DBPM', 'BPM', 'VORP'],
      dtype='object')

In [88]:
df3_cleaned = clean_nba_multi_team_records(
    df = df3, 
    df_multi_team = df3_multi_team,
    cols_to_drop = ['Rk', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'Awards', 'Player-additional']
)

df3_cleaned

,Player,PER,TS%,3PAr,FTr,ORB%,DRB%,TRB%,AST%,STL%,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Amen Thompson,18.9,0.594,0.111,0.374,8.9,14.0,11.5,20.4,2.0,...,13.5,20.0,6.5,3.8,10.3,0.167,1.6,1.0,2.6,3.4
1,Kevin Durant,21.1,0.641,0.327,0.339,1.6,14.8,8.3,20.7,1.1,...,13.5,27.1,7.5,3.2,10.7,0.180,4.4,0.1,4.5,4.7
2,Desmond Bane,16.9,0.607,0.354,0.287,3.9,9.8,6.8,19.3,1.5,...,10.8,23.3,4.8,2.6,7.4,0.129,1.6,-0.2,1.4,2.3
3,Toumani Camara,11.3,0.578,0.664,0.154,5.0,11.7,8.4,10.4,1.6,...,13.1,16.3,2.1,2.7,4.8,0.084,-1.0,0.0,-1.0,0.7
4,Jabari Smith Jr.,13.5,0.570,0.501,0.215,4.5,17.0,10.8,7.3,1.0,...,9.0,18.2,3.4,3.3,6.6,0.118,-0.5,-0.2,-0.7,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Stanley Umude,11.6,0.500,0.500,0.000,0.0,0.0,0.0,18.8,6.9,...,0.0,12.0,0.0,0.0,0.0,0.165,-6.7,7.1,0.4,0.0
578,Colby Jones,12.9,0.333,0.667,0.000,0.0,63.1,32.1,37.8,0.0,...,0.0,17.8,0.0,0.0,0.0,0.124,-3.2,5.7,2.4,0.0
579,Noa Essengue,-11.9,0.000,0.667,0.000,0.0,0.0,0.0,0.0,7.8,...,0.0,20.8,-0.1,0.0,-0.1,-0.417,-20.7,-3.0,-23.7,0.0
580,Trentyn Flowers,16.7,0.667,0.333,0.000,17.9,0.0,8.8,30.5,0.0,...,25.0,27.8,0.0,0.0,0.0,0.023,1.7,-2.7,-1.0,0.0
581,Darius Brown II,-7.7,0.000,0.000,0.000,0.0,36.5,18.3,0.0,0.0,...,0.0,14.0,0.0,0.0,0.0,-0.269,-16.3,-2.4,-18.7,0.0

In [90]:
# Merging 3 dataframes

merged_df = pd.merge(pd.merge(df1_cleaned, df2_cleaned, on='Player'), df3_cleaned, on='Player')
merged_df

,Player,Rk,Age,Team,Pos,G,GS,MP,FG,FGA,...,TOV%,USG%,OWS,DWS,WS,WS/48,OBPM,DBPM,BPM,VORP
0,Amen Thompson,1,23,HOU,PG,79,79,2953,9.4,17.7,...,13.5,20.0,6.5,3.8,10.3,0.167,1.6,1.0,2.6,3.4
1,Kevin Durant,2,37,HOU,SF,78,78,2840,12.6,24.2,...,13.5,27.1,7.5,3.2,10.7,0.180,4.4,0.1,4.5,4.7
2,Desmond Bane,3,27,ORL,SG,82,82,2756,10.2,21.0,...,10.8,23.3,4.8,2.6,7.4,0.129,1.6,-0.2,1.4,2.3
3,Toumani Camara,4,25,POR,PF,82,82,2731,6.9,15.6,...,13.1,16.3,2.1,2.7,4.8,0.084,-1.0,0.0,-1.0,0.7
4,Jabari Smith Jr.,5,22,HOU,PF,77,77,2705,8.1,18.0,...,9.0,18.2,3.4,3.3,6.6,0.118,-0.5,-0.2,-0.7,0.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
577,Stanley Umude,578,26,SAS,SG,2,0,7,6.9,13.7,...,0.0,12.0,0.0,0.0,0.0,0.165,-6.7,7.1,0.4,0.0
578,Colby Jones,579,23,DET,SG,1,0,7,6.9,20.7,...,0.0,17.8,0.0,0.0,0.0,0.124,-3.2,5.7,2.4,0.0
579,Noa Essengue,580,19,CHI,PF,2,0,6,0.0,23.4,...,0.0,20.8,-0.1,0.0,-0.1,-0.417,-20.7,-3.0,-23.7,0.0
580,Trentyn Flowers,581,20,CHI,SF,2,0,6,15.6,23.4,...,25.0,27.8,0.0,0.0,0.0,0.023,1.7,-2.7,-1.0,0.0
581,Darius Brown II,582,26,CLE,SG,1,0,3,0.0,16.0,...,0.0,14.0,0.0,0.0,0.0,-0.269,-16.3,-2.4,-18.7,0.0

In [92]:
merged_df.columns

Index(['Player', 'Rk', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA',
       'FG%', '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA',
       'FT%', 'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS',
       'Dist.', '% of FGA by 0-3 feet', '% of FGA by 3-10 feet',
       '% of FGA by 10-16 feet', '% of FGA by 16 feet - 3P',
       '% of FGA by 3P area', '% of 2PFG Ast'd', '% of 3P Ast'd',
       '%3PA Corner', 'PER', 'TS%', '3PAr', 'FTr', 'ORB%', 'DRB%', 'TRB%',
       'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'OWS', 'DWS', 'WS', 'WS/48',
       'OBPM', 'DBPM', 'BPM', 'VORP'],
      dtype='object')

In [94]:
# Check null values
merged_df.isnull().sum()

Player                       0
Rk                           0
Age                          0
Team                         0
Pos                          0
G                            0
GS                           0
MP                           0
FG                           0
FGA                          0
FG%                          0
3P                           0
3PA                          0
3P%                         35
2P                           0
2PA                          0
2P%                          3
eFG%                         0
FT                           0
FTA                          0
FT%                         19
ORB                          0
DRB                          0
TRB                          0
AST                          0
STL                          0
BLK                          0
TOV                          0
PF                           0
PTS                          0
Dist.                        0
% of FGA by 0-3 feet         0
% of FGA by 3-10 feet        0
% of FGA by 10-16 feet       0
% of FGA by 16 feet - 3P     0
% of FGA by 3P area          0
% of 2PFG Ast'd              8
% of 3P Ast'd               66
%3PA Corner                 35
PER                          0
TS%                          0
3PAr                         0
FTr                          0
ORB%                         0
DRB%                         0
TRB%                         0
AST%                         0
STL%                         0
BLK%                         0
TOV%                         0
USG%                         0
OWS                          0
DWS                          0
WS                           0
WS/48                        0
OBPM                         0
DBPM                         0
BPM                          0
VORP                         0
dtype: int64

In [96]:
# Clean the null vales to zero

merged_df = merged_df.fillna(0)
merged_df.isnull().sum()

Player                      0
Rk                          0
Age                         0
Team                        0
Pos                         0
G                           0
GS                          0
MP                          0
FG                          0
FGA                         0
FG%                         0
3P                          0
3PA                         0
3P%                         0
2P                          0
2PA                         0
2P%                         0
eFG%                        0
FT                          0
FTA                         0
FT%                         0
ORB                         0
DRB                         0
TRB                         0
AST                         0
STL                         0
BLK                         0
TOV                         0
PF                          0
PTS                         0
Dist.                       0
% of FGA by 0-3 feet        0
% of FGA by 3-10 feet       0
% of FGA by 10-16 feet      0
% of FGA by 16 feet - 3P    0
% of FGA by 3P area         0
% of 2PFG Ast'd             0
% of 3P Ast'd               0
%3PA Corner                 0
PER                         0
TS%                         0
3PAr                        0
FTr                         0
ORB%                        0
DRB%                        0
TRB%                        0
AST%                        0
STL%                        0
BLK%                        0
TOV%                        0
USG%                        0
OWS                         0
DWS                         0
WS                          0
WS/48                       0
OBPM                        0
DBPM                        0
BPM                         0
VORP                        0
dtype: int64

In [100]:
# Export the dataframe to csv
merged_df.to_csv('/Users/stevenyeung/Desktop/My Document/Exercise/Clustering/Dataset/NBA_stat.csv')